require "./assembler.rb"

puts "[ Compile Start ]"

# The directories of all test .asm files in this course
load_paths = { "add": ["Add"], "max": ["Max", "MaxL"], "rect": ["Rect", "RectL"], "pong": ["Pong", "PongL"] }

load_paths.each_key do |key|
  load_paths[key].each do |file_name|
    path_to_file = "../#{key.to_s}/#{file_name}"
    Assembler.new(path_to_file).compile # Compile .asm to .hack with the assembler I designed
    # Compare my compiled file with the .cmp.hack file generated by CPU Simulator of this course
    success = FileUtils.compare_file("#{path_to_file}.hack", "#{path_to_file}.cmp.hack");
    # Print the result
    puts (success ? "[ Success ]" : "[ Error ]") << " Built & Compared #{file_name}.hack"
  end
end

puts "[ Compile End ]"